---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ include "pool.fullName" . }}"
  labels:
    {{- include "pool.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.storage }}"
