{{- if .Values.ingress.enabled -}}
{{- $domain := include "app.domain" . -}}
{{- $fullName := include "app.fullName" . -}}
{{- $svcPort := 8080 -}}

{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $domain | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-web
              servicePort: 8080
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-web
              servicePort: 8080
    {{- end }}
  {{- end }}
